- name: Check if epel-release is installed
  command: rpm -q epel-release
  register: rpm_check
  ignore_errors: true
  failed_when: "rpm_check.rc != 0"

- name: Install epel-release if not installed
  command: yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  when: rpm_check|failed

- name: Disable epel repositories
  replace: dest=/etc/yum.repos.d/epel.repo regexp='enabled=1' replace='enabled=0'

- name: Install nagios-nrpe
  yum: name={{ item }} enablerepo=epel state=present
  with_items:
  - nrpe

- name: Ensure iptables is configured to allow nrpe traffic (port 5666/tcp)
  lineinfile:
    dest: /etc/sysconfig/iptables
    state: present
    regexp: "-A INPUT -p tcp -m state --state NEW -m tcp --dport 5666 -j ACCEPT"
    insertafter: "-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT"
    line: "-A INPUT -p tcp -m state --state NEW -m tcp --dport 5666 -j ACCEPT"
    backup: yes
  notify: restart iptables

- name: Enable and start nagios nrpe service
  service: name=nrpe state=started enabled=yes

- name: Install nagios-plugins
  yum: name={{ item }} enablerepo=epel state=present
  with_items:
  - nagios-plugins-disk
  - nagios-plugins-users
  - nagios-plugins-tcp
  - nagios-plugins-load
  - nagios-plugins-http
  - nagios-plugins-procs

- name: Configure nrpe
  template: src=nrpe.cfg.j2 dest=/etc/nagios/nrpe.cfg
  notify: restart nrpe

- name: Configure checks
  copy: src=nagios-common.cfg dest=/etc/nrpe.d/nagios-common.cfg owner=root group=root mode=0755
